# Generated by Django 3.2 on 2021-04-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country_capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
